name: arxiv_helper
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - python=3.10
  - pip
  - pip:
    - arxiv
    - PyGithub
    - openai
    - httpx
    - PyQt6
    - requests
    - pyinstaller
    - pymupdf>=1.23.0
    - huggingface_hub>=0.20.0
    - markdown
    - PyQt6-WebEngine
